### ISSUE TITLE
[BUG] Localization analysis doesn't run at single-frame image

### ISSUE THREAD

**Issue by Yujin-Bao** [python-microscopy/python-microscopy#1098]
**Describe the bug**
I use `LatGaussFitFR` to analyse localization data from a one-frame image of 1um beads. An error shows in `pymeclusterofone` terminal.

**To Reproduce**
1. For `point finding`, I set the threshold to 5 and run `test this frame` to make sure for each bead, there is only one candidate region to be fitted, labeled by the small green square.
2. This is only a one-frame image, so set `start at` as 0, and cancel `subtract background in fit`, then click `go`
![image](https://user-images.githubusercontent.com/80548133/128936074-ab0f2a73-57f2-4f6c-8cc4-896d0cf5f1c1.png)
3. See error in `pymeclusterofone` terminal: `tables.exceptions.NoSuchNodeError: group / does not have a child named Events`.
![image](https://user-images.githubusercontent.com/80548133/128937648-4cdc7944-dae8-4f59-8726-33ddefced6b6.png)

**Expected behavior**
I expect to see 2D Gaussian fittings in each small green square as well as their acceptance and rejection.

**Comment by David-Baddeley** [comment]
Hmm, there looks to be multiple things going on here, and the tracebacks are not particularly useful ...

- What format is the input data? The tracebacks would suggest that it's .h5 formatted, but lacks an events table. (This might not actually be a critical error - it might get handled fine in normal operation, but we might be seeing the error because something else fails when we try and handle it)
- The second error (NoneType is not iterable) is probably more important. The only thing that I can think of is that this might be caused by an empty array (i.e. no molecules detected and fit).

In line with this error, it's worth pointing out that to disable background subtraction, you need to both uncheck the `subtract background in fit` box **and** set the `Background:` range to `0:0`. With the settings as shown, you will be attempting to use background subtraction for object detection, but not for fitting. Revamping the GUI here to show separate "subtract background for detection" and "subtract background in fit" options (which would be much more understandable) has been on the  TODO list for a while now, but as it stands, having anything other than `0:0` in the background range implies subtract background for detection. There might also be subtle differences in how this works when testing and when analyising.

**Comment by David-Baddeley** [comment]
PS - if you could share the data you're trying to fit that might help further debugging.

**Comment by Yujin-Bao** [comment]
Thank you for the reply, David! 
- The format of the input data is `.tif` file, but I did create a `.md` metadata file as it suggested in the documetation. However, I only set the minimum set of metadata parameters.
- I set the `Background` range to `0:0` and ran it again, but still got the same problem. 
-  I'll send you the original data through email for further reference.

**Comment by David-Baddeley** [comment]
Thanks for the data! Have got it ~90% fixed (at least enough that the analysis will run and generate correct output data).

**Comment by Yujin-Bao** [comment]
Hi David! Thanks for solving the problem! However, when I tried it again, the traceback in `PymeImage` reported another error, saying `Names must only include alphanumeric characters and underscore`. But I think I have the proper name for this. Could you tell me how I could solve this?
![image](https://user-images.githubusercontent.com/80548133/130094981-015592a2-c954-4ee4-9433-c8ef0f2cb024.png)

**Comment by zacsimile** [comment]
@lukasfue has the same problem. I tried this on my mac and it worked fine, so I suspect this is windows-specific.

**Comment by zacsimile** [comment]
Backslashes again, as well as Windows's file-naming scheme including a `:` in every path. Fixed in #1104.
