### ISSUE TITLE
[BUG] Can't run simple recipe anymore - issue finding input datasource

### ISSUE THREAD

**Issue by csoeller** [python-microscopy/python-microscopy#1295]
**Describe the bug**
I was trying to run a simple recipe module in `dh5view`. Got an error `Input "input" is missing from namespace; keys: []`. I swear this used to work??!!

**To Reproduce**
1. Open image with `dh5view`
2. Add `Threshold`module in recipe tab with default arguments

```
Error in recipe module: <PYME.recipes.processing.Threshold object at 0x1519c0540>

Traceback (most recent call last):

  File "/Users/csoe002/Documents/src/PYMEsrc/pyme38/PYME/recipes/recipe.py", line 221, in execute

    m.check_inputs(self.namespace)

  File "/Users/csoe002/Documents/src/PYMEsrc/pyme38/PYME/recipes/base.py", line 206, in check_inputs

    raise MissingInputError('Input "%s" is missing from namespace; keys: %s' % (input, keys))

PYME.recipes.base.MissingInputError: Input "input" is missing from namespace; keys: []

Traceback (most recent call last):

  File "/Users/csoe002/Documents/src/PYMEsrc/pyme38/PYME/recipes/recipe.py", line 221, in execute

    m.check_inputs(self.namespace)

  File "/Users/csoe002/Documents/src/PYMEsrc/pyme38/PYME/recipes/base.py", line 206, in check_inputs

    raise MissingInputError('Input "%s" is missing from namespace; keys: %s' % (input, keys))

PYME.recipes.base.MissingInputError: Input "input" is missing from namespace; keys: []



The above exception was the direct cause of the following exception:



Traceback (most recent call last):

  File "/Users/csoe002/Documents/src/PYMEsrc/pyme38/PYME/recipes/recipeGui.py", line 605, in OnAddModule

    self.recipes.activeRecipe.invalidate_data()

  File "/Users/csoe002/Documents/src/PYMEsrc/pyme38/PYME/recipes/recipe.py", line 46, in invalidate_data

    self.execute()

  File "/Users/csoe002/Documents/src/PYMEsrc/pyme38/PYME/recipes/recipe.py", line 263, in execute

    raise RecipeExecutionError('Recipe execution failed in module %s' % self._failing_module._module_name, self ) from e

PYME.recipes.recipe.RecipeExecutionError: Recipe execution failed in module processing.Threshold
```

**Expected behavior**
I swear this used to work. Maybe somebody can please explain if this is a user error or if recently the interface has changed.

Recipe in textform is:

```yaml
- processing.Threshold:
    inputName: input
    outputName: filtered_image
```

**Platform:**
latest code from Master (`22.10.03.post0.dev[git]85d65a224ec6`) on macos ARM M2

**Comment by David-Baddeley** [comment]
If you run the recipe from the menu (Recipes->Run Recipe) or by pressing F5  it will still run as expected (and the above error  can be ignored) ... that said, a fix should land soon ... 

The error was introduced when trying to align the PYMEVis and PYMEImage/dh5view pipelines, (previously in PYMEImage had both recipes, and a pipeline used for point data (overlays, localisations etc ...) but there namespaces were separate, making it really hard to e.g. overlay anything generated in a recipe with the image data (you needed to special case a copy of the data into the dh5view "pipeline", and the special casing would generally only work for the "output" of the recipe - you couldn't walk your way through the recipes intermediate results the way you can in PYMEVis. 

To assist with debugging some isosurface stuff, I changed things so that the recipe and pipeline namespaces were common (as in PYMEVis). This common namespace is probably a good idea long term, but still has a few wrinkles and crept in ahead of schedule after getting mixed up with a bunch of bugfixes.  The specific error you saw is because I hadn't turned off automatic execution of the pipeline recipe (and hence, now, the dh5view recipe) which meant that the recipe was executing as soon as the module was added, rather than only when told to run from the menu.  The `input` data is only injected into the recipe when you run  it from the menu. This particular bug is easily fixed by turning off automatic execution (which should be done anyway for PYMEImage recipes as they are often sufficiently computationally costly that you don't want them executing automatically). 

There are, however, a couple of additional wrinkles which make me uncertain whether to just merge the simple fix, or to roll-back to the previous behaviour. These are:
- When you open a localisation file to e.g. overlay on the data, pipeline manipulations (e.g. changing point filtering) will only take effect when you manually run the recipe (with auto-execution turned off).
- If you manually run the recipe (e.g. after updating filter settings) it will run the entire recipe, potentially including any computationally expensive image manipulation bits (this is somewhat mitigated by the incremental execution) 
- If you have opened a localisation data set, the standard pipeline bits to deal with this (Pipelinify, ProcessColour, FilterTable) will be added to the current recipe (and the recipe will fail if the point data is not loaded). This might not always be desired.

These wrinkles are pretty niche in their effects, but still need considering.

**Comment by csoeller** [comment]
Thanks for fixing, works now ok...
