### ISSUE TITLE
[BUG] --root option doesn't work for PYMEClusterOfOne

### ISSUE THREAD

**Issue by zacsimile** [python-microscopy/python-microscopy#1307]
If you pass a custom `--root` option to `pymeclusterofone`, it creates a `LOGS` directory at your location of choice, but if you run any tasks, the data is still saved in the default `PYMEData` folder.

**Comment by zacsimile** [comment]
However, specifying `dataserver-root` in `config.yaml` does work.

**Comment by David-Baddeley** [comment]
This is a bit more complex - it does work for the dataserver itself, but not for anything which bypasses the dataserver because the data resides on the local node, which is the case for most IO. Probably also not for scoring of tasks (`is_local()` and similar). In practice, it will probably be respected for the `__aggregate` endpoints, but not direct saving. The simplest solution is probably simply to remove the `--root` option from PYMEClusterOfOne.
