### ISSUE TITLE
Progress bars and time estimates

### ISSUE THREAD

**Issue by zacsimile** [python-microscopy/python-microscopy#238]
Add progress bars and time estimates to operations that take longer than few seconds.

**Comment by barentine** [comment]
Something like `PYME.Deconv.deconvDialogs.DeconvProgressDialog`.

some candidates:
- [ ] surface generation
- [ ] ripley's
- [ ] pairwise distances
- [ ] signed-distance w/ surface calc

**Comment by zacsimile** [comment]
Good candidates! I'd swap octree generation (it's pretty fast) for surface generation.

**Comment by David-Baddeley** [comment]
While nice, progress bars are a bit of a hassle to implement - you need to embed a progress callback in your computational code. For this to be easy to implement there should be an outside iterative loop that does a fair bit of work on each iteration(1-5s) so you can call the progress callback on each iteration. Deconvolution is probably about the easiest case (which is why it's the only thing which currently has a progress bar). In general progress reporting is going to make our algorithmic code harder to read and maintain (there is a reason that none of the numpy, scipy, skimage etc ... functions do progress reporting). If you have progress bar, you should also have some way of cancelling which is also tricky (say you added a module to the recipe - canceling would require rolling back, removing that module, and then making sure the normal invalidation settings etc were restored.)

We should think very hard about whether this is something we really want to spend effort on. What might be a reasonable compromise is to change the menu items to indicate that this is likely to be a slow process (e.g. by appending "[slow]" to the item names), or potentially even prompt the user for confirmation before starting if the process is super slow. I used to do this for a couple of the functions, although I don't think any survived - with the old python version of event clumping which was super slow I prompted the user to check if they wanted to continue if the number of localisations was over a certain threshold.

**Comment by zacsimile** [comment]
This came up in a PYMEVisualize demo for the lab today. While progress bars would be the best, I think users would settle for being able to check "is this process still running or did it crash?" For users who don't know where to check for tracebacks, this can become confusing. PYME will sometimes (albeit rarely) just hang after failing, and you won't know the process has failed unless you check the terminal. Plus, the terminal is still covered in wx deprecation warnings, which do continue popping up after a process has failed, and make it harder to find the error traceback.

**Comment by David-Baddeley** [comment]
I used to change the mouse cursor to a timer and then change it back once finished as an indication that something was happening. We could look at setting that up again. Would need robust error handling (putting everything in a try ... finally block or, potentially even better, making a `with_timer_cursor` context manager).

**Comment by barentine** [comment]
`with_timer_cursor` context manager would be nice

**Comment by David-Baddeley** [comment]
Another option would be to have a shuttle-style progress indicator (maybe in the status bar) that showed that something was happening, but not the actual progress - like the netscape loading icon (that dates me !). The key to any of these is making sure that they get cancelled on error - the problem with my old ones is that you'd get a failure and the mouse pointer would stay as a timer.

I'll have a little play and see what I can find.

Better error handling and reporting would also help.

**Comment by David-Baddeley** [comment]
Working thoughts on a solution below:

a context manager:

```python
with computation_in_progress('Short description of what you are doing'):
    #expensive code here
```

the `computation_in_progress` context manager does the following:

- changes the mouse pointer to a timer and back again on success or failure
- changes the status bar text to display the description
- changes the status bar text on exit to either indicate successful completion or failure (would need to check whether context managers can tell whether their exit function was called due to an exception or not)
- ideally, displays a dialog with the traceback on error (potentially even with a report error button)

**Comment by David-Baddeley** [comment]
the `__exit__` method takes exception info as arguments - should be possible.

**Comment by zacsimile** [comment]
I like this solution. A report error button would be excellent.

**Comment by David-Baddeley** [comment]
I'm really excited by it - will see if I can bash it out

**Comment by David-Baddeley** [comment]
Preliminary version now in repo - only enabled for pairwise features and some of the tracking stuff for now, but wondering if we shouldn't just wrap every menu item in it - ie change `AUIFrame.AddMenuItem()` so every call from the menu gets wrapped in the context manager. 

The error dialog is possibly still a bit rough, but arguably still better than the status quo.

The only thing which might speak against this would be those modules which display a dialog first (although that might not be a big deal - the issue would be potential mouse pointer confusion).

**Comment by zacsimile** [comment]
Very cool! I'm in favor of wrapping everything in the error context manager. 

I have a potential solution for getting around the dialog problem. `wx.Window` has a `FindFocus()` method that returns a pointer to the object in focus. We could check if this object is  a `wx.Dialog` and change the cursor accordingly.

**Comment by zacsimile** [comment]
I think the context manager approach is more than sufficient for now. Possible additional move would be to have a recipe decorator like `@long_runtime` that throws an alert on recipe configuration.
