### ISSUE TITLE
[BUG] HTSMLM scope GUI locks during 3 frame-per-step calibration protocol

### ISSUE THREAD

**Issue by barentine** [python-microscopy/python-microscopy#527]
**Describe the bug**
Running `PYMEAcquire -i init_htsms.py` and starting the `htsms-calibration.py` protocol locks up the GUI, sometimes indefinitely, but sometimes you get the `stop` button enabled and can click it and eventually kill the protocol. Otherwise none of the GUI updates, including the current frame. The series indeed spools, but if the `stop` is disabled and we have to terminate the instance we're out of luck as far as events go (they do not get spooled in that case, of course). 

**Additional context**
- this is happening with short integration times, e.g. 25 or 50 ms. Haven't tried longer

**Platform (please complete the following information - or copy-paste from error dialog if shown):**
 - OS: [e.g. Win10] win10
 - Python version: 3.6
 - numpy version: 1.19
 - wxpython version [if a UI bug]: 4.0.4

**Comment by David-Baddeley** [comment]
Protocols with short z dwell times are generally problematic. This needs to be documented better, but the recommended way of taking z-calibration stacks is to use the z-stack functionality, **not** protocols. Due to their very loose synchronisation and the fact that the movement occurs on frame groups rather than frames, z-stepping in protocols relies on the length of time spent at each z step being both >> the piezo motion time and >> 100 ms. 

If you are absolutely dead set on using protocols for taking z-stacks, put the camera in single-shot mode first (or potentially rig something using software triggers like the tile-triggered protocol),  but be aware that this is abusing protocols for something that they aren't designed for and that you are likely to run into issues.

**Comment by barentine** [comment]
Thanks David. Meanwhile I've just been using longer exposure times, but I'll probably software trigger it. Going to close this issue, but agree it would be great to document this for others
