### ISSUE TITLE
[BUG] Test this Frame incorrectly displays detected blinks when using SplitterShiftEstFR and SplitterFitFNR

### ISSUE THREAD

**Issue by lukasfue** [python-microscopy/python-microscopy#847]
**Describe the bug**
When testing a frame for localization using current settings, it typically will highlight the detected points in green boxes. When one attempts to do this with both SplitterShiftEstFR and SplitterFitFNR, these green boxes and displayed incorrectly. The first channels green boxes appear to be fine, the second channels boxes appear to overlap the first channel's image but is shifted down a bit, despite the second channel's image being to the right of the first's. If you look carefully, the boxes that aren't highlighting any beads in this image (either in between actual beads or below the image entirely) follow the same pattern as the beads in the right channel. So it seems the detection is working fine, just the boxes aren't displayed in the right place.

**To Reproduce**
1. Load two-color beads image
2. Click "test this frame" using either SplitterShiftEstFR or SPlitterFitFNR as the "Type"
3. See that the displayed green boxes on the current frame are incorrect

**Expected behavior**
Green boxes displayed correctly on top of the detected beads/blinks

**Screenshots**
![image](https://user-images.githubusercontent.com/36608397/107653852-132f9100-6c50-11eb-8bfa-c638fa7e8d0a.png)

**Comment by David-Baddeley** [comment]
This has been on my radar for a while - the current display code is really old and specific to an up-down splitting arrangement (where channel 2 is below channel 1). Ultimately the splitter preview code needs to be completely re-written. So far, it hasn't been painful enough for me to actually do anything about it. The new implementation should be as an overlay, rather than as an integral part of the image viewer.

There are also a few things in the pipeline which will impact the fix and/or require another re-write, namely the multi-view and splitter integration (i.e. splitting with more than 2 views) and, potentially an OpenGL version of the image viewer, so I've been punting it until they are in (or at least we know what they are going to look like.
